export const SET_BOARDS = "SET_BOARDS"
export const ADD_NEW_BOARD = "ADD_NEW_BOARD"
export const DELETE_BOARD = "DELETE_BOARD"
export const RENAME_BOARD = "RENAME_BOARD"

export const SET_TODO_LISTS = "SET_TODO_LISTS"
export const ADD_NEW_TODOLIST = "ADD_NEW_TODOLIST"
export const DELETE_TODOLIST = "DELETE_TODOLIST"
export const RENAME_TODO_LIST_TITLE = "RENAME_TODO_LIST_TITLE"

export const SET_TASKS = "SET_TASKS"
export const ADD_NEW_TASK = "ADD_NEW_TASK"
export const CHANGE_TASK_TITLE = "CHANGE_TASK_TITLE"