export const ADD_NEW_BOARD = "ADD_NEW_BOARD"

export const ADD_NEW_TODOLIST = "ADD_NEW_TODOLIST"
export const CHANGE_TODO_LIST_TITLE = "CHANGE_TODO_LIST_TITLE"

export const ADD_NEW_TASK = "ADD_NEW_TASK"
export const CHANGE_TASK_TITLE = "CHANGE_TASK_TITLE"